server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: notification-service

  datasource:
    url: ${NOTIFICATION_DB_URL:jdbc:postgresql://notification-postgres:5435/notification_db}
    username: ${NOTIFICATION_DB_USER:postgres}
    password: ${NOTIFICATION_DB_PASSWORD:postgres}

services:
  auth:
    url: ${AUTH_SERVICE_URL:http://auth-service}
  bot:
    url: ${BOT_SERVICE_URL:http://bot-service}