services:

  auth-postgres:
    image: postgres:16-alpine
    container_name: auth-postgres
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: UTC+3
    ports:
      - "${AUTH_DB_PORT}:5432"
    tmpfs:
      - /var/lib/postgresql/data:rw,noexec,nosuid,size=256m
    shm_size: "256m"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h 127.0.0.1 -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 15
      start_period: 5s
    restart: unless-stopped


  ticket-postgres:
    image: postgres:16-alpine
    container_name: ticket-postgres
    environment:
      POSTGRES_DB: ${TICKET_DB_NAME}
      POSTGRES_USER: ${TICKET_DB_USER}
      POSTGRES_PASSWORD: ${TICKET_DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: UTC+3
    ports:
      - "${TICKET_DB_PORT}:5432"
    tmpfs:
      - /var/lib/postgresql/data:rw,noexec,nosuid,size=256m
    shm_size: "256m"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h 127.0.0.1 -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 15
      start_period: 5s
    restart: unless-stopped


  notification-postgres:
    image: postgres:16-alpine
    container_name: notification-postgres
    environment:
      POSTGRES_DB: ${NOTIFICATION_DB_NAME}
      POSTGRES_USER: ${NOTIFICATION_DB_USER}
      POSTGRES_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: UTC+3
    ports:
      - "${NOTIFICATION_DB_PORT}:5432"
    tmpfs:
      - /var/lib/postgresql/data:rw,noexec,nosuid,size=256m
    shm_size: "256m"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h 127.0.0.1 -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 15
      start_period: 5s
    restart: unless-stopped


  redis:
    image: redis:7-alpine
    container_name: auth-redis
    ports:
      - "6379:6379"
    restart: unless-stopped