server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: gateway

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:auth-redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

app:
  security:
    jwt:
      issuer: ticket-system-auth
      audience: ticket-system
      jwk-set-uri: ${APP_SECURITY_JWT_JWK_SET_URI:http://auth-service:8082/.well-known/jwks.json}


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    urls:
      - name: auth-service
        url: /auth/v3/api-docs
      - name: ticket-service
        url: /ticket/v3/api-docs
      - name: notification-service
        url: /notification/v3/api-docs
    urlsPrimaryName: auth-service