server:
  port: 8086

spring:
  application:
    name: tests-module

tests:
  urls:
    baseUrl: "http://localhost"
    gateway:
      port: "8081"
    auth:
      port: "8082"
    ticket:
      port: "8084"
      commonUrl: "/tickets"
      createComment: "/%s/comments"
      changeStatus: "/%s/status"
      assigneeTicket: "/%s/assignee"
      createTicket: ""
      updateTicket: ""
    notification:
      port: "8083"
      commonUrl: "/notifications"
      getAllNotifications: "/get"