server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: ticket-service

  datasource:
    url: ${TICKET_DB_URL:jdbc:postgresql://localhost:5434/ticket_db}
    username: ${TICKET_DB_USER:ticket_user}
    password: ${TICKET_DB_PASSWORD:ticket_password}

services:
  notification:
    url: ${NOTIFICATION_SERVICE_URL:http://notification-service:8083}
    timeout:
      connect: 500
      read: 1000